export const PAPERT_ALLOWED_TOOLS = [
	// Canonical Papert default tool names
	"Edit",
	"ExitPlanMode",
	"Glob",
	"Grep",
	"ListFiles",
	"Lsp",
	"ReadFile",
	"ReadManyFiles",
	"SaveMemory",
	"Shell",
	"Task",
	"TodoWrite",
	"WebFetch",
	"WriteFile",

	// snake_case aliases used by some models/prompts
	"task",
	"list_directory",
	"read_file",
	"grep_search",
	"search_file_content",
	"glob",
	"lsp",
	"edit",
	"replace",
	"write_file",
	"read_many_files",
	"run_shell_command",
	"save_memory",
	"todo_write",
	"web_fetch",
	"web_search",
	"google_web_search",
	"exit_plan_mode",

	// compatibility tool names observed from model outputs
	"message",
	"Message",
	"slack",
	"Slack",
	"SendFileToChat",
	"send_file_to_chat",
] as const;
